pipeline{
    agent any
    environment {
        NODE_ENV = "test"
        TEST_DB_USER="postgres"
        TEST_DB_PASSWORD="123"
        TEST_DB_HOST="host.docker.internal"
        TEST_DB_PORT="5432"
        TEST_DB_DATABASE="PetHealthTrackerTestDB"
        TEST_EMAIL_USER="vetpetapplication@gmail.com"
        TEST_EMAIL_PASSWORD="ewwf rmkc jnin ybcw"
    }
    stages{
        stage("build"){
            steps{
                dir("backend"){
                    sh "npm install"
                }
            }
        }
        stage("integration tests"){
            steps{
                dir("backend"){
                    sh "npm test"
                }
            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}