pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                dir("backend"){
                    bat "npm install"
                }
            }
        }
        stage("integration tests"){
            steps{
                dir("backend"){
                    bat "npm test"
                }
            }
        }
    }
    post{
        always{
            deleteDir()
        }
    }
}